format = """
$character\
$directory\
[ ▶](bold bg:#7aa2f7 fg:#cfc9c2)[ ](fg:#7aa2f7)\
$cmd_duration\
$new_line
"""

right_format = """
[](fg:#e0af68)$sudo[ ](fg:#e0af68)\
[](fg:#15161e)\
$git_branch$git_commit$git_status\
$python
[](fg:#15161e)\
"""

[character]
success_symbol = "[](fg:#9ece6a)[■](bold bg:#9ece6a fg:#15161e)[ ](fg:#9ece6a)"
error_symbol = "[](fg:#f7768e)[×](bold bg:#f7768e fg:#15161e)[ ](fg:#f7768e)"
format = "$symbol"

[directory]
style = "fg:#ebebeb bg:#15161e"
format = "[](fg:#15161e)[$path ]($style)[](fg:#15161e bg:#7aa2f7)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Codes" = "󰅴"
"Data" = "󰆼"

[cmd_duration]
min_time = 60000
format = "[](fg:#e0af68)[󰚭 $duration](bold bg:#e0af68 fg:#15161e)[ ](fg:#e0af68)"

[sudo]
symbol = ""
format = "[$symbol]($style)"
style = "bg:#e0af68 fg:#24283b"
disabled = false

[username]
style_root = "bold bg:#e0af68 fg:#f7768e"
style_user = "bold bg:#e0af68 fg:#24283b"
format = "[]($style)"
show_always = true

[git_branch]
symbol = ''
truncation_length = 4
truncation_symbol = ':'
style = "bg:#15161e fg:#e0af68"
format = "[$branch -> ]($style)"
# ignore_branches = ['master', 'main']

[git_commit]
commit_hash_length = 7
style = "bg:#15161e fg:#e0af68"
format = "[#$hash -> ]($style)"

[git_status]
style = "fg:#7aa2f7 bg:#15161e"
format = "[$all_status ⇡${ahead_count}⇣${behind_count} ]($style)"

[python]
symbol = " "
style = "bg:#15161e fg:#9ece6a"
format = "[$symbol$version $virtualenv]($style)"
